# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('status', models.CharField(choices=[('BU', 'Строительство'), ('RE', 'Ремонт'), ('EX', 'Эксплуатация')], default='EX', max_length=2, verbose_name='Статус')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
